version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - /appveyor.yml
environment:
  COVERALLS_REPO_TOKEN:
    secure: SCMU2gqW4Mu8XForDKfnBKvXLfnZ84GrO+nzCo5VP3nAB/hyoJq7n/JqjbJ9P6Pq
build_script:
- cmd: >-
    dotnet restore src\WebStore\

    dotnet build src\WebStore\

    dotnet pack src\WebStore\
test_script:
- cmd: 
  dotnet test src\WebStore.Tests\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  
  nuget install OpenCover -OutputDirectory packages -Version 4.6.166
    
  dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools
    
  .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" ""src\GameOfLife.xUnit.Tests\bin\Release\netcoreapp2.0\GameOfLife.xUnit.Tests.dll"" -noshadow -appveyor" -filter:"+[GameOfLife*]*" -oldStyle -output:opencoverCoverage.xml
    
   $coveralls = ".\tools\csmacnz.coveralls.exe"
   
   & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: h77TLfult0fo5y6zngQdnSfZ5KuX2frCaVaM/LYw/mCCkzdVQp5Rdzuhg2HX+7B5
  skip_symbols: true
  artifact: /.*\.nupkg/
