version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet restore src\WebStore\
    
    dotnet build src\WebStore\
    
    dotnet pack src\WebStore\
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: 6865xw7+RRpWe5xkjXRJdH5BZ95KxqsPAUYmG5TZwpSNDojHVHQP4iH8swNRyokY
  skip_symbols: true
  artifact: /.*\.nupkg/
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
environment:
  COVERALLS_REPO_TOKEN:
    secure: SCMU2gqW4Mu8XForDKfnBKvXLfnZ84GrO+nzCo5VP3nAB/hyoJq7n/JqjbJ9P6Pq
