version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - /appveyor.yml
environment:
  COVERALLS_REPO_TOKEN:
    secure: SCMU2gqW4Mu8XForDKfnBKvXLfnZ84GrO+nzCo5VP3nAB/hyoJq7n/JqjbJ9P6Pq
build_script:
- ps: >-
    dotnet restore src\WebStore\

    dotnet build src\WebStore\

    dotnet pack src\WebStore\
test_script:
- ps: >-
    dotnet tool install coveralls.net --tool-path tools

    dotnet test src\WebStore.Tests\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    csmacnz.Coveralls --opencover -i src\WebStore.Tests\coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: h77TLfult0fo5y6zngQdnSfZ5KuX2frCaVaM/LYw/mCCkzdVQp5Rdzuhg2HX+7B5
  skip_symbols: true
  artifact: /.*\.nupkg/
